name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-workflow:
    runs-on: ubuntu-22.04

    steps:
      - name: Manual step
        run: | 
          echo "Hellow, World"
          echo "Hellow, World 2"