name: Dependent Multi Jobs Workflow

on:
  workflow_dispatch:

jobs:
  dependent-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Workflow Job
        run: |
          echo "Hello, First Workflow!"

  second-workflow-jobs:
    runs-on: ubuntu-latest
    needs: [dependent-workflow-job]

    steps:
      - name: Second Workflow Job
        run: |
          echo "Hello, Second Workflow!"


  third-workflow-jobs:
    runs-on: ubuntu-latest
    needs: [second-workflow-jobs]

    steps:
      - name: Third Workflow Job
        run: |
          echo "Hello, Third Workflow!"
        