name: Conditional Workflow

on:
  push:
    paths:
      - "Backend/**"

jobs:
  conditional-workflow:
    runs-on: ubuntu-22.04

    steps:
      - name: Build Backend Image
        run: |
          echo "Hello, Build Backend Image!"

  docker-build-workflow:
    uses: ahmmedsabbirbddev/github-action/.github/workflows/11-reusable-workflow.yml@main
  