name: Predefined Workflow

on:
  workflow_dispatch:

jobs:
  predefined-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: NodeJs Version
        run: node -v

      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v4
        with:
          node-version: 20.0.0

      - name: NodeJs Version
        run: node -v